added final stages

diff --git a/jenkins file b/jenkins file
--- a/jenkins file
+++ b/jenkins file
@@ -105,9 +105,9 @@ pipeline {
             steps {
                 echo 'Cleaning Up Local Docker Images...'
                 sh '''
-                    docker rmi arunrade/booking-ms:latest || echo "Image not found or already deleted"
+                    docker rmi chandan669/booking-ms:latest || echo "Image not found or already deleted"
                     docker rmi booking-ms:latest || echo "Image not found or already deleted"
-                    docker rmi 703671926591.dkr.ecr.ap-south-1.amazonaws.com/booking-ms:latest || echo "Image not found or already deleted"
+                    docker rmi 084828560148.dkr.ecr.us-east-1.amazonaws.com/booking-ms:latest || echo "Image not found or already deleted"
                     docker image prune -f
                 '''
                 echo 'Local Docker Images Cleaned Up Successfully!'
