Update jenkins file

diff --git a/jenkins file b/jenkins file
--- a/jenkins file
+++ b/jenkins file
@@ -7,7 +7,7 @@ pipeline {
 	}
 
 	tools {
-		maven 'mvn_3.9.9'
+		maven 'maven'
 	}
 
 	stages {
@@ -47,5 +47,71 @@ pipeline {
 				sh 'mvn clean package'
 				echo 'WAR Artifact Created Successfully!'
 			}
-}
+		}
+		stage('Build & Tag Docker Image') {
+			steps {
+				echo 'Building Docker Image with Tags...'
+				sh "docker build -t arunrade/booking-ms:latest -t booking-ms:latest ."
+				echo 'Docker Image Build Completed!'
+			}
+		}
+		stage('Docker Image Scanning') {
+			steps {
+				echo 'Scanning Docker Image with Trivy...'
+				echo 'Docker Image Scanning Completed!'
+			}
+		}
+		stage('Push Docker Image to Docker Hub') {
+			steps {
+				script {
+					withCredentials([string(credentialsId: 'dockerhubCred', variable: 'dockerhubCred')]) {
+						sh 'docker login docker.io -u arunrade -p ${dockerhubCred}'
+						echo 'Pushing Docker Image to Docker Hub...'
+						sh 'docker push arunrade/booking-ms:latest'
+						echo 'Docker Image Pushed to Docker Hub Successfully!'
+					}
+				}
+			}
+		}
+		stage('Push Docker Image to Amazon ECR') {
+			steps {
+				script {
+					withDockerRegistry([credentialsId: 'ecr:ap-south-1:ecr-credentials', url: "https://703671926591.dkr.ecr.ap-south-1.amazonaws.com"]) {
+						echo 'Tagging and Pushing Docker Image to ECR...'
+						sh '''
+                            docker images
+                            docker tag booking-ms:latest 703671926591.dkr.ecr.ap-south-1.amazonaws.com/booking-ms:latest
+                            docker push 703671926591.dkr.ecr.ap-south-1.amazonaws.com/booking-ms:latest
+                        '''
+						echo 'Docker Image Pushed to Amazon ECR Successfully!'
+					}
+				}
+			}
+		}
+		stage('Upload Docker Image to Nexus') {
+			steps {
+				script {
+					withCredentials([usernamePassword(credentialsId: 'nexus-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
+						sh 'docker login http://43.205.114.241:8085/repository/booking-ms/ -u admin -p ${PASSWORD}'
+						echo "Push Docker Image to Nexus : In Progress"
+						sh 'docker tag booking-ms 43.205.114.241:8085/booking-ms:latest'
+						sh 'docker push 43.205.114.241:8085/booking-ms'
+						echo "Push Docker Image to Nexus : Completed"
+					}
+				}
+			}
+		}
+        stage('Clean Up Local Docker Images') {
+            steps {
+                echo 'Cleaning Up Local Docker Images...'
+                sh '''
+                    docker rmi arunrade/booking-ms:latest || echo "Image not found or already deleted"
+                    docker rmi booking-ms:latest || echo "Image not found or already deleted"
+                    docker rmi 703671926591.dkr.ecr.ap-south-1.amazonaws.com/booking-ms:latest || echo "Image not found or already deleted"
+                    docker image prune -f
+                '''
+                echo 'Local Docker Images Cleaned Up Successfully!'
+            }
+        }
+	}
 }
